##' @importFrom utils data
NULL

##' \code{ExoData} results for FoxA1 ChIP-exo experiment
##' 
##' \code{ExoData} object, generated with \code{ChIPexoQual} and the
##' file:
##' 
##' \itemize{
##' \item ChIPexo_carroll_FoxA1_mouse_rep3_chr1.bam
##' }
##' 
##' @return An \code{ExoData} object with the 3rd replicate of the FoxA1 
##' experiment from \code{ChIPExoQualExample}.
##' @docType data
##' @name exoExample
##' @usage data(exoExample)
##' @format ExoData object, which are \code{GRanges} with additional columns.
NULL

##' \code{list} of \code{GRanges} objects with the blacklists generated by the ENCODE and 
##' modENCODE projects.
##' 
##' @return A \code{list} with the blacklists listed in https://sites.google.com/site/anshulkundaje/projects/blacklists.
##' @docType data
##' @name blacklists
##' @usage data(blacklists)
##' 
##' @format \code{list} of \code{GRanges} objects.
NULL